// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AddAPIKey(arg1:string,arg2:string):Promise<void>;

export function AgentClaimHandover(arg1:string):Promise<void>;

export function AgentResolveConversation(arg1:string):Promise<void>;

export function AgentSendMessage(arg1:string,arg2:string):Promise<void>;

export function DeleteAPIKey(arg1:number):Promise<void>;

export function DeleteFAQ(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function DeleteSOP(arg1:number):Promise<void>;

export function DisconnectWA():Promise<void>;

export function GetAPIKeys():Promise<Array<dto.APIKeySafe>>;

export function GetBusinessConfig():Promise<dto.BusinessConfig>;

export function GetFAQs():Promise<Array<dto.FAQ>>;

export function GetInbox():Promise<Array<dto.ConversationSummary>>;

export function GetMessages(arg1:string,arg2:number):Promise<Array<dto.Message>>;

export function GetNotes():Promise<Array<dto.Note>>;

export function GetProducts():Promise<Array<dto.Product>>;

export function GetQRCode():Promise<string>;

export function GetSOPs():Promise<Array<dto.SOP>>;

export function GetWAStatus():Promise<dto.WAStatus>;

export function ImportFAQFromCSV(arg1:string):Promise<number>;

export function ImportNoteFromFile(arg1:string,arg2:Array<number>):Promise<void>;

export function ImportProductFromCSV(arg1:string):Promise<number>;

export function ReorderFAQs(arg1:Array<number>):Promise<void>;

export function SaveBusinessConfig(arg1:dto.BusinessConfig):Promise<void>;

export function SaveFAQ(arg1:dto.FAQ):Promise<void>;

export function SaveNote(arg1:dto.Note):Promise<void>;

export function SaveProduct(arg1:dto.Product):Promise<void>;

export function SaveSOP(arg1:dto.SOP):Promise<void>;

export function ToggleAPIKey(arg1:number,arg2:boolean):Promise<void>;
