// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAPIKey(arg1, arg2) {
  return window['go']['main']['App']['AddAPIKey'](arg1, arg2);
}

export function AgentClaimHandover(arg1) {
  return window['go']['main']['App']['AgentClaimHandover'](arg1);
}

export function AgentResolveConversation(arg1) {
  return window['go']['main']['App']['AgentResolveConversation'](arg1);
}

export function AgentSendMessage(arg1, arg2) {
  return window['go']['main']['App']['AgentSendMessage'](arg1, arg2);
}

export function DeleteAPIKey(arg1) {
  return window['go']['main']['App']['DeleteAPIKey'](arg1);
}

export function DeleteFAQ(arg1) {
  return window['go']['main']['App']['DeleteFAQ'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function DeleteSOP(arg1) {
  return window['go']['main']['App']['DeleteSOP'](arg1);
}

export function DisconnectWA() {
  return window['go']['main']['App']['DisconnectWA']();
}

export function GetAPIKeys() {
  return window['go']['main']['App']['GetAPIKeys']();
}

export function GetBusinessConfig() {
  return window['go']['main']['App']['GetBusinessConfig']();
}

export function GetFAQs() {
  return window['go']['main']['App']['GetFAQs']();
}

export function GetInbox() {
  return window['go']['main']['App']['GetInbox']();
}

export function GetMessages(arg1, arg2) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2);
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetProducts() {
  return window['go']['main']['App']['GetProducts']();
}

export function GetQRCode() {
  return window['go']['main']['App']['GetQRCode']();
}

export function GetSOPs() {
  return window['go']['main']['App']['GetSOPs']();
}

export function GetWAStatus() {
  return window['go']['main']['App']['GetWAStatus']();
}

export function ImportFAQFromCSV(arg1) {
  return window['go']['main']['App']['ImportFAQFromCSV'](arg1);
}

export function ImportNoteFromFile(arg1, arg2) {
  return window['go']['main']['App']['ImportNoteFromFile'](arg1, arg2);
}

export function ImportProductFromCSV(arg1) {
  return window['go']['main']['App']['ImportProductFromCSV'](arg1);
}

export function ReorderFAQs(arg1) {
  return window['go']['main']['App']['ReorderFAQs'](arg1);
}

export function SaveBusinessConfig(arg1) {
  return window['go']['main']['App']['SaveBusinessConfig'](arg1);
}

export function SaveFAQ(arg1) {
  return window['go']['main']['App']['SaveFAQ'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SaveProduct(arg1) {
  return window['go']['main']['App']['SaveProduct'](arg1);
}

export function SaveSOP(arg1) {
  return window['go']['main']['App']['SaveSOP'](arg1);
}

export function ToggleAPIKey(arg1, arg2) {
  return window['go']['main']['App']['ToggleAPIKey'](arg1, arg2);
}
